### ISSUE TITLE
Can you write a detailed description of the use of thanks

### ISSUE THREAD

**Issue by szsyzx** [xtnctx/Google-Keyword-Search#2]
Can you write a detailed description of the use of thanks

**Comment by xtnctx** [comment]
Hi @szsyzx, I will. I think I might re-create this for public use or make a package for this one.

**Comment by szsyzx** [comment]
Is it possible to do key monitoring? For example, I want to monitor keyword A on Google search, and push alerts if new pages involving A appear, or if pushing to slack, discord.



---Original---
From: "Ryan Christopher ***@***.***&gt;
Date: Fri, Aug 5, 2022 15:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xtnctx/Google-Keyword-Search] Can you write a detaileddescription of the use of thanks (Issue #2)




 
Hi @szsyzx, I will. I think I might re-create this for public use or make a package for this one.

**Comment by xtnctx** [comment]
Done recreating, this one does not use the `CLIENT_SECRET_FILE`. Just put your values in the `keyword` and `text_to_find`. Also read the comments I made for better understanding on how this works.

https://github.com/xtnctx/Google-Keyword-Search/tree/test


----------------------
About your question, this can only search specific words on your keywords you put on search bar. Pushing in your discord is different.
